molecular_descriptor: rdkit
molecule_database: smiles_responses.txt
similarity_measure: tanimoto
tasks:
  compare_target_molecule:
    identify_closest_furthest:
      out_file_path: molSim-ui_output.txt
    plot_settings:
      plot_color: orange
      plot_title: Compared to Target Molecule
    target_molecule_smiles: FC(F)(F)C(F)(F)C(F)C(F)C(F)(F)F
  show_property_variation_w_similarity:
    most_dissimilar: true
    property_file: smiles_responses.txt
    similarity_plot_settings:
      plot_color: red
  visualize_dataset:
    pairwise_heatmap_settings:
      annotate: false
      cmap: viridis
    plot_settings:
      plot_color: green
      plot_title: Entire Dataset
verbose: true
