# This is a basic workflow to help you get started with Actions

name: Generate Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      # Runs a set of commands using the runners shell
      - name: Install Dependencies
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          # checkout the respoitory
          # git clone https://github.com/VlachosGroup/molSim
          # cd molSim
          # install our dependencies
          conda install python=3.7
          conda install -c rdkit rdkit
          conda list
          python -m pip install rdkit-pypi
          python -m pip install networkx==2.1
          python -m pip install -r requirements.txt
          python -m pip install -e .
          python -m pip install sphinx sphinx-rtd-theme m2r mistune==0.8.4
      
      - name: Generate Documentation
        run: |
          # regen rst files
          m2r README.md 
          m2r implemented_metrics.md
          mv README.rst docs
          mv implemented_metrics.rst docs
          cd docs
          sphinx-apidoc -f -o . ..
          make html
          mv _build/html/* .
          mv _build/doctrees/* .
          echo "" > .nojekyll
        
          # add and commit but DO NOT push changes to rst and html files
          git add .
          git commit -m "temp commit" -a || true
          
          git merge -s ours --allow-unrelated-histories origin/gh-pages
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Push Changes
        run:
          git push
