name: Generate Docs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          # install our dependencies
          conda install python=3.7
          conda install -c rdkit rdkit
          conda list
          python -m pip install rdkit-pypi
          python -m pip install networkx==2.1
          python -m pip install -r requirements.txt
          python -m pip install -e .
          python -m pip install sphinx sphinx-rtd-theme m2r mistune==0.8.4
      
      - name: Generate Documentation
        run: |
          rm README.rst || true
          rm docs/README.rst || true
          rm implemented_metrics.rst || true
          rm docs/implemented_metrics.rst || true
          m2r README.md
          m2r implemented_metrics.md
          mv README.rst docs
          mv implemented_metrics.rst docs
          cd docs
          rm *.html
          rm _sources/*
          rmdir _sources
          rm _static/*
          rmdir _static
          sphinx-apidoc -f -o . ..
          make html
          mv _build/html/* .
          mv _build/doctrees/* .
          echo "" > .nojekyll
          git add .
          git commit -m "Automated Docs Update" -a || true
          git push -f
