name: Run Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          # install our dependencies
          conda install python=3.7
          conda install -c rdkit rdkit
          conda list
          python -m pip install rdkit-pypi
          python -m pip install networkx==2.1
          python -m pip install openpyxl
          python -m pip install -r requirements.txt
          python -m pip install -e .
          python -m pip install sphinx sphinx-rtd-theme m2r mistune==0.8.4
      
      - name: Run Tests
        run: |
          python -m unittest discover
